### ISSUE TITLE
一个bug报告与问一些问题。

### ISSUE THREAD

**Issue by xsjqqq123** [0xmalloc/c-log#6]
大神，你好。
多次init有什么特殊作用吗？一个线程中init，其它线程都可以用了？似乎没有对log文件大小进行限制啊？

bug:
在linux 创建的目录不可写，导致init时的路径有目录就失败。
c文件中25行左右：
原文：if (mkdir (p_logdir, S_IREAD | S_IWRITE ) < 0)
改为：S_IRWXU | S_IRWXG | S_IROTH | S_IXOTH
就可以了。

**Comment by 0xmalloc** [comment]
这个库确实没考虑这么复杂的情况  因为主要用于server端研发  日志打在什么路径 用什么账号启动process  具备什么功能权限都会事先约定好   感谢提交的这个case
