### ISSUE TITLE
有可以用于windows系统的版本吗？

### ISSUE THREAD

**Issue by hbhuyt** [0xmalloc/c-log#7]
这个c-log好像只能在linux环境下运行吧，有没有适用于windows的版本呢？
谢谢！

**Comment by hbhuyt** [comment]
不好意思，是我弄错了，这个应该是在c++ 0x上编译的吧，有能在vs2008下编译的版本吗？

**Comment by 0xmalloc** [comment]
我用GCC编译的   在vs2008上是有什么问题吗？

**Comment by 0xmalloc** [comment]
需要支持c++11的编译器
